### ISSUE TITLE
Error: The JSON passed to chckt.checkout was not properly formatted as JSON

### ISSUE THREAD

**Issue by alkapawn** [Adyen/adyen-web-sdk-sample-code#15]
Hi everyone,

I've downloaded and set up the adyen-web-sdk-sample here, means I've created the authentication.ini file with my data from adyen.

When I start the demo in Firefox the page stays blank and the console shows the following error messages:
ERROR: ### parseSetupJSON::init:: e= SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
at https://checkoutshopper-test.adyen.com/checkoutshopper/assets/js/sdk/checkoutSDK.1.3.0.min.js:3:88715
################################################
Error: The JSON passed to chckt.checkout was not properly formatted as JSON (typeof data: undefined, data was not JSON) at checkoutSDK.1.3.0.min.js:3:89096

I've tried to see what initiateCheckout() is receiving and the param jsonResponse is "undefined" in console.
Also I've echoed $paymentSessionData in index.php and it shows the following message: 

""{\"error\":{\"code\":403,\"message\":\"Forbidden\",\"requested URI\":\"\\\/checkout\\\/\\\/services\\\/PaymentSetupAndVerification\\\/v37\\\/paymentSession\"}}" "

Can please anybody tell me what I'm doing wrong here?

Thank you!!
Regards

Alex

**Comment by Trigalti** [comment]
This means either your API key or merchantAccount is wrong.
The connection is succesfully made to our back-end.

Please contact support@adyen.com if you need help with account set up / further investigation. (It might just be a setting).

**Comment by alkapawn** [comment]
Thank you very much, this solved my problem! I've used the Checkout Demo Server API Key which obviously is not working for this purpose 👍
