### ISSUE TITLE
What is my merchantAccount? Where to find checkoutAPIkey?

### ISSUE THREAD

**Issue by pmochine** [Adyen/adyen-web-sdk-sample-code#16]
I'm sorry for asking this. But it's not obvious.

Somehow I've two accounts one with mynameCOM and myname.

Nonetheless, if I'm looking for the checkoutAPIkey there is none to be found: 

Yes, I see the "Checkout Demo Server API Key (x-demo-server-api-key)" but I think that should be not the key. Above it, I see the API Key but come on. It just does not say anywhere checkoutAPIkey. API Key refers to Payment token. So my guess is that I should generate the key and it should be called Payment Token API Key?

Then comes the other question. What is my merchantAccount? Just try to google it, you won't find anything to it... Do you mean perhaps Merchant Name? Or Adyen Account? There are some differences. The first would be "my name"  the second would be "myname".

I can only tap into the darkness and I added the Payment Token API Key as checkoutAPIkey, and "myname" as  Merchant Name. 

But still the code explodes and I get the errors:

```
checkoutSDK.1.3.0.min.js:3 ERROR: ### parseSetupJSON::init:: e= SyntaxError: Unexpected token u in JSON at position 0

Uncaught Error: The JSON passed to chckt.checkout was not properly formatted as JSON (typeof data: undefined, data was not JSON)

Failed to load resource: the server responded with a status of 404 (Not Found)
```

That really baffles me, you want to earn money but why do you throw these simple obstacles so one cannot even see the demo of the payment system....

**Comment by Trigalti** [comment]
Hello @pmochine documentation on where to find the apiKey and merchantAccount can be found here:
https://docs.adyen.com/developers/checkout/web-sdk/quick-start-web

Your "Company account" will have COM appended to it, where as the merchant account will be the sub account of your company. (Imagine having one company with multiple "stores").
