### ISSUE TITLE
404 link to docs.adyen.com

### ISSUE THREAD

**Issue by tobiasmuehl** [Adyen/adyen-web-sdk-sample-code#2]
- In [setupCall.js](https://github.com/Adyen/adyen-web-sdk-sample-code/blob/master/assets/js/setupCall.js) on line 5 there's a link to the adyen docs that results in a 404: https://docs.adyen.com/developers/checkout-javascript-sdk/styling-secured-fields
- In [index.php](https://github.com/Adyen/adyen-web-sdk-sample-code/blob/master/index.php) in line 42: https://docs.adyen.com/support/getting-started/step-1-create-a-test-account

**Comment by olutsenko** [comment]
Fixed. Thanks for spotting this!
