### ISSUE TITLE
Any Chance for the Checkout SDK to be added to NPM?

### ISSUE THREAD

**Issue by marbuser** [Adyen/adyen-web-sdk-sample-code#21]
Hey there,

Sorry to ask this here since I know this is reserved for issues regarding the repo, but I tried contacting general Adyen support and they were pretty unhelpful so hopefully some of the maintainers of this could answer this for me.

Can we expect an NPM package(s) of the checkout SDK? You have an NPM package for the CSE and I think one for the checkout SDK would also be pretty cool.

As someone who uses libraries like Vue and React, it's pretty annoying to have to just hardcode the sdk into a html file, and I think an NPM package would benefit in a lot of way such as;
- Easier updating. Instead of checking release notes on the Adyen website and changing the version number on the URL, the NPM version will just get updated.
- Easier implementation. We can use ES6 import statements and such rather than straight up hardcoding the script tag into a HTML file.

Hopefully you guys will consider this since I think it makes a lot of sense and will make a lot of developers lives a lot easier.

Another couple of questions I have that are unrelated are;
- Since you have the CSE as an NPM package, is it possible currently for me to use the checkout SDK and indicate I want to use the CSE locally rather than from Adyen servers? I've had some minor connection issues in the past with the CSE hosted on Adyen and think it will be more reliable if I host it myself.
- I'm using the Checkout SDK in the context of a REST API, and was wondering what the "official" way of implementation was? I've pretty much been following the docs here; (https://docs.adyen.com/developers/checkout/web-sdk) but wanted to ensure I'm doing everything securely and correctly.

I've got a payment endpoint that the client communicates with that on the server will call paymentSession and will do all the required stuff such as make an order number, grab pricing from database, etc... Then it returns the session to the client.

Then after payment is made I have a verify endpoint that takes the payload and checks and ensures it was successful and such.

Hopefully you can help. Thanks.

**Comment by star-jar** [comment]
+1 please

**Comment by skylarmb** [comment]
+1

**Comment by Trigalti** [comment]
Unfortunately, this is not part of our plans. Our Web SDK is a hosted solution and a multitude of variables are included while serving the SDK.
