### ISSUE TITLE
How to use the “Cost Estimation API” with Web SDK?

### ISSUE THREAD

**Issue by frequentredundancy** [Adyen/adyen-web-sdk-sample-code#22]
In a project I'm working on, we need to be able to grab the fees the customer's payment method will incur BEFORE they pay.

For example, if they select PaySafeCard and the amount they need to pay is $20, they select PaySafeCard and the price will update on the button on the form before they click it as $22.52 (.12 + 12%)

Or if they click Credit Card and enter in an AMEX, it will update to $20.91.

I was wondering if this is possible? I did notice you guys have the “Cost Estimation API” but doesn't seem like there is anyway to use that with the Web SDK.

If not, what is the best way for me to handle this while still using the Web SDK?

Any help is appreciated.

**Comment by Trigalti** [comment]
This will be possible starting our new version of the SDK (1.9.7).
You are able to add surcharges on the customer area:
Account -> Checkout -> Bottom of the page (surcharges).

Now, for usage of the cost estimation API & advanced usage (like dynamic surcharge on the credit cards), I would suggest using our components together with the API.
This way, you have full control over the amount you send in through back-end:
https://docs.adyen.com/checkout/api-integration/
