### ISSUE TITLE
TypeError: Cannot read property 'validate' of undefined

### ISSUE THREAD

**Issue by voslartomas** [Adyen/adyen-web-sdk-sample-code#23]
Hello, trying to implement adyen checkout via paymentSession. I am able to see the form with card inputs, but when I fill it up I can see error after finishing each input (typing last character of input).

Any ideas what can be wrong?

<img width="1665" alt="screenshot 2019-02-27 at 17 12 28" src="https://user-images.githubusercontent.com/1945040/53504821-f590ad80-3ab2-11e9-94fa-6265dad593a9.png">

## versions

Using react with nextjs.

<script type="text/javascript" src="https://checkoutshopper-test.adyen.com/checkoutshopper/assets/js/sdk/checkoutSDK.1.9.2.min.js"></script>

**Comment by philippfo9** [comment]
how have you been able to solve this?

**Comment by voslartomas** [comment]
You need to contact tech support, they will fix it for your account.
