### ISSUE TITLE
Allow credit Card onyl

### ISSUE THREAD

**Issue by njdumngalon** [Adyen/adyen-web-sdk-sample-code#25]
Hi,

Just wanna ask if how can I customized the displayed payment methods. Was trying to allow credit card only but having some error that I cant seems to find a solution.

This is my initialization and customization on the form

![Screenshot from 2019-11-27 16-14-21](https://user-images.githubusercontent.com/38255774/69705735-157ffb00-1131-11ea-989e-1e17b47ebf09.png)

then I encounter this error and the form is not displaying

![Screenshot from 2019-11-27 16-15-48](https://user-images.githubusercontent.com/38255774/69705795-39dbd780-1131-11ea-8909-f8a6ff53fd0b.png)

With out customization this is my default

![Screenshot from 2019-11-27 16-17-05](https://user-images.githubusercontent.com/38255774/69705880-6394fe80-1131-11ea-8514-f95e4ba6eeb0.png)

wanted to remove the online banking, convenience store and the more link

Thank you in advance :)

**Comment by pabloai** [comment]
Hi, thanks for reaching us.

You have multiple possible solutions here:

1. Use the `allowedPaymentMethods` property in the payment session configuration object to only allow credit cards:

```js
const paymentSessionConfig = {
    // ...
    allowedPaymentMethods: ['visa', 'mc', 'amex']
};
```

2. Add/remove the payment methods you need in the Customer Area. For this, please refer to our [payment methods page](https://docs.adyen.com/payment-methods#add-payment-methods-to-your-account).

3. If you just started working in your integration, I'd strongly recommend you migrate to a newer integration. For only displaying cards you can use our [Card Component](https://docs.adyen.com/payment-methods/cards#collect-with-web-component). In case you need to fully customize the UI, you can use the [Custom Card Component](https://docs.adyen.com/payment-methods/cards/custom-card-component) and to display a list of all the available payment methods, you can use the [Drop-in integration](https://docs.adyen.com/payment-methods/cards/web-drop-in).

All these integrations use the JS file, the same Backend integration and a similar API.

For more information, please contact our [Support team](https://support.adyen.com/hc/en-us).

Cheers!
