### ISSUE TITLE
ShopperIP parameter doesn't exist in /setup API spec

### ISSUE THREAD

**Issue by tobiasmuehl** [Adyen/adyen-web-sdk-sample-code#4]
In [`api/serverCall.php:55`](https://github.com/Adyen/adyen-web-sdk-sample-code/blob/master/api/serverCall.php#L55) the sample code passes a parameter named "shopperIP" to Adyen.

This parameter is not part of the API spec in the [developers documentation](https://docs.adyen.com/developers/in-app-integration/checkout-api-reference)

**Comment by Trigalti** [comment]
Thank you, will add it to our documentation.

**Comment by Trigalti** [comment]
This has been added to our API documentation:
https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v32/setup
