### ISSUE TITLE
ShopperLocale has wrong format

### ISSUE THREAD

**Issue by tobiasmuehl** [Adyen/adyen-web-sdk-sample-code#5]
In [`payment/order.php:44`](https://github.com/Adyen/adyen-web-sdk-sample-code/blob/master/payment/order.php#L44) the code is passing `en-US`.

According to the [documentation](https://docs.adyen.com/developers/in-app-integration/checkout-api-reference) the correct format uses an underscore `en_US`.

**Comment by Trigalti** [comment]
We are accepting both formats as a fallback 👍

**Comment by tobiasmuehl** [comment]
Ah, ok
