### ISSUE TITLE
Add change log 

### ISSUE THREAD

**Issue by tobiasmuehl** [Adyen/adyen-web-sdk-sample-code#7]
Poking around at your web server, I'm confused which version should be used. The demo code uses version 1.0.0, yet you also serve a version 1.1.0. I did not find this mentioned in any documentation. Can you publish a change-log and offer versioning information?

Whats the difference between the following?

- https://checkoutshopper-test.adyen.com/checkoutshopper/assets/js/sdk/checkoutSDK.1.0.min.js
- https://checkoutshopper-test.adyen.com/checkoutshopper/assets/js/sdk/checkoutSDK.1.0.0.min.js
- https://checkoutshopper-test.adyen.com/checkoutshopper/assets/js/sdk/checkoutSDK.1.1.0.min.js
- https://checkoutshopper-test.adyen.com/checkoutshopper/assets/js/sdk/checkoutSDK.1.1.1.min.js
- https://checkoutshopper-test.adyen.com/checkoutshopper/assets/js/sdk/checkoutSDK.1.1.2.min.js

**Comment by Trigalti** [comment]
Thank you for your feedback.
We have changelogs ready to be published and will do so on our documentation platform.
I will attach links to the notes coming week.

**Comment by Trigalti** [comment]
- We have released a better documented version 1.2.0
- We have updated our documentation : https://docs.adyen.com/developers/checkout/web-sdk
- We have published some release notes (more to follow)
- We have updated the code sample on this git to 1.2.0 and it's features and configuration

**Comment by Trigalti** [comment]
A link to the release notes for 1.2.0;
https://docs.adyen.com/developers/checkout/checkoutreleasenotes/checkout-sdk-1-2-0-release-notes
